POST http://localhost:8080/api/v1/accounts
Content-Type: application/json

# This creates a new account with balance of 42069
{
  "balance": 42069.0
}

###
POST http://localhost:8080/api/v1/accounts
Content-Type: application/json
{
  "balance": 42070.0
}

###

GET http://localhost:8080/api/v1/accounts