### Test 1: Testing POST /blogger
POST http://localhost:8080/blogger
Content-Type: application/json

{
  "email": "user001@apper.ph",
  "name": "First User",
  "password": "pass123"
}

### Test 1.1: Add one more blogger

POST http://localhost:8080/blogger
Content-Type: application/json

{
"email": "user002@apper.ph",
"name": "Second User",
"password": "pass456"
}

### Test 2: Get Blogger
### Format: GET http://localhost:8080/blogger/<id>
GET http://localhost:8080/blogger/a3becf3c-df45-4120-a276-127ddc51d94f

### Test 3: Get All Bloggers

GET http://localhost:8080/blogger

### Test 4: Create Blog for User 1

POST http://localhost:8080/blogger/blog
Content-Type: application/json

{
  "title": "This is the title for 1st blog of User001",
  "body": "This is the actual content of User001 blog1",
  "blogger_id": "a3becf3c-df45-4120-a276-127ddc51d94f"
}

### Test 4.1: Create another blog for User 1

POST http://localhost:8080/blogger/blog
Content-Type: application/json

{
  "title": "This is the title for 2nd blog of User001",
  "body": "This is the actual content of User001 blog2",
  "blogger_id": "a3becf3c-df45-4120-a276-127ddc51d94f"
}


### Test 4.2: Create a blog for User 2

POST http://localhost:8080/blogger/blog
Content-Type: application/json

{
  "title": "This is the title for 1st blog of User002",
  "body": "This is the actual content of User001 blog1",
  "blogger_id": "eb7c640d-2454-490b-b88f-a6e8e2574529"
}

### Test 5: Get All Blogs
GET http://localhost:8080/blogger/blog

### Test 6: Get a Blog from its id
GET http://localhost:8080/blogger/blog/63446239-2a2a-4722-a701-5d686d888ef6

### Test 7: Update a blog of User 1
PUT http://localhost:8080/blogger/blog/63446239-2a2a-4722-a701-5d686d888ef6
Content-Type: application/json

{
  "title": "Updated User1 Blog1: SKT #1",
  "body": "SKT will win #Worlds2023",
  "blogger_id": "08aae12c-76b4-4a0c-8e2f-c2c7c440064d"
}

### Test 8: Get All blogs by blogger (User 1)
### This also confirms Test 7
GET http://localhost:8080/blogger/blog/blogger/a3becf3c-df45-4120-a276-127ddc51d94f