### Test 1: Testing POST /blogger
POST http://localhost:8080/blogger
Content-Type: application/json

{
  "email": "user001@apper.ph",
  "name": "First User",
  "password": "pass123"
}

### Test 1.1: Add one more blogger

POST http://localhost:8080/blogger
Content-Type: application/json

{
"email": "user002@apper.ph",
"name": "Second User",
"password": "pass456"
}

### Test 2: Get Blogger
### Format: GET http://localhost:8080/blogger/<id>
GET http://localhost:8080/blogger/8d0297d5-fc5a-4fba-999c-9dc07de95874

### Test 3: Get All Bloggers

GET http://localhost:8080/blogger

### Test 4: Create Blog for User 1

POST http://localhost:8080/blog
Content-Type: application/json

{
  "title": "This is the title for 1st blog of User001",
  "body": "This is the actual content of User001 blog1",
  "blogger_id": "8d0297d5-fc5a-4fba-999c-9dc07de95874"
}

### Test 4.1: Create another blog for User 1

POST http://localhost:8080/blog
Content-Type: application/json

{
  "title": "This is the title for 2nd blog of User001",
  "body": "This is the actual content of User001 blog2",
  "blogger_id": "8d0297d5-fc5a-4fba-999c-9dc07de95874"
}


### Test 4.2: Create a blog for User 2

POST http://localhost:8080/blog
Content-Type: application/json

{
  "title": "This is the title for 1st blog of User002",
  "body": "This is the actual content of User001 blog1",
  "blogger_id": "386da5c2-4237-4932-ad44-2cae2821b9d1"
}

### Test 5: Get All Blogs
GET http://localhost:8080/blog

### Test 6: Get a Blog from its id
GET http://localhost:8080/blog/9d59aaff-a70d-4e82-b2b8-277bd82917cf

### Test 7: Update a blog of User 1
PUT http://localhost:8080/blog/9d59aaff-a70d-4e82-b2b8-277bd82917cf
Content-Type: application/json

{
  "title": "Updated User1 Blog1: SKT #1",
  "body": "SKT will win #Worlds2023",
  "blogger_id": "08aae12c-76b4-4a0c-8e2f-c2c7c440064d"
}

### Test 8: Get All blogs by blogger (User 1)
### This also confirms Test 7
GET http://localhost:8080/blog/blogger/8d0297d5-fc5a-4fba-999c-9dc07de95874