### Add Account 1
POST http://localhost:8080/account
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Add Account 2
POST http://localhost:8080/account
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "password": "password456"
}

### Add Account 3
POST http://localhost:8080/account
Content-Type: application/json

{
  "firstName": "Michael",
  "lastName": "Jackson",
  "email": "michael.jackson@example.com",
  "password": "password789"
}

### Get all
GET http://localhost:8080/account

### Get Account 1
GET http://localhost:8080/account/0e937752-8320-433e-9a87-34bc6921ddf9

### Update Account 1
PUT http://localhost:8080/account/0e937752-8320-433e-9a87-34bc6921ddf9
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Bravo",
  "email": "jbravomegaLUL@example.com",
  "password": "XDD42069"
}

### Get Account 1
GET http://localhost:8080/account/0e937752-8320-433e-9a87-34bc6921ddf9

### Delete Account 3
DELETE http://localhost:8080/account/7192d427-3e79-422d-898e-6461be44bacc

### Get all
GET http://localhost:8080/account











