### No account registered yet
GET http://localhost:8080/account

### Add Account 1
POST http://localhost:8080/account
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Add Account 2
POST http://localhost:8080/account
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "password": "password456"
}

### Add Account 3
POST http://localhost:8080/account
Content-Type: application/json

{
  "firstName": "Michael",
  "lastName": "Jackson",
  "email": "michael.jackson@example.com",
  "password": "password789"
}

### Get all
GET http://localhost:8080/account

### Get Account 1 (Copy paste it from previous)
GET http://localhost:8080/account/33ab5e36-6974-4eff-b72e-7f8243f8737f

### Get Unknown (this returns error as intended)
GET http://localhost:8080/account/42069

### Update Account 1
PUT http://localhost:8080/account/33ab5e36-6974-4eff-b72e-7f8243f8737f
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Bravo",
  "email": "jbravomegaLUL@example.com",
  "password": "XDD42069"
}

### Get Account 1 (the same with above as udpated!)
GET http://localhost:8080/account/33ab5e36-6974-4eff-b72e-7f8243f8737f

### Delete Account 1
DELETE http://localhost:8080/account/33ab5e36-6974-4eff-b72e-7f8243f8737f

### Get all (no more Johhny Bravo!)
GET http://localhost:8080/account











